### ISSUE TITLE
NPCR has requested a change to UIHO

### ISSUE THREAD

**Issue by howew** [imsweb/algorithms#107]
We need to add 6 counties to the lookup table for UIHO.  I will do this and submit a merge request when I have clarity on what should go into the facility column for these counties.

*Del Norte County (06015)
*Humboldt County (06023)
*Orange County (06059)
*San Joaquin (06077)
*Siskiyou (06093)
*Trinity (06105)

**Comment by depryf** [comment]
Is there a reason that the UIHO data doesn't cover all counties? Is it supposed to? I am asking because if it's supposed to have a value for all of them, we should add a unit test to make sure the data contains all counties and not run into this again. If it's not supposed to, then there isn't anything we can do about this other than adding the missing ones when they are identified...

**Comment by howew** [comment]
It should only contain a row if it actually is a UIHO county.

**Comment by depryf** [comment]
Thanks for clarifying. 

The build is still failing; I will merge once its' fixed. Let me know if you need help (it looks like a class is still using the * imports, so maybe you are not using the correct code style in IntelliJ?

**Comment by howew** [comment]
I'm not getting notifications (again).  I literally only changed the lookup table and the changelog.

How do I view TeamCity and apply the coding styles again?

**Comment by depryf** [comment]
The changes are available with version 2.18
