### ISSUE TITLE
Change implementation of census tract poverty indicator data provider

### ISSUE THREAD

**Issue by depryf** [imsweb/algorithms#12]
To optimize memory usage, the data provider uses a mechanism of multiplying the result for each year categories, and dividing it during the actual calculation. That mechanism is difficult to understand when reading the code, and more importantly, it doesn't scale. We just added new year categories and now we have to multiple the value by a million. That just doesn't work well. At all.

**Comment by howew** [comment]
I was thinking the same thing while updating it.  A string would make it more straightforward - but I'm assuming there were concerns about memory - otherwise you probably would have used one to begin with.

**Comment by depryf** [comment]
This is done, the new code is much cleaner, and I don't think the memory foot print will become much bigger than what it was.

@howew, could you please take a look at my changes since you are involved in maintaining this class? 

One thing that I found suspicious is that in CensusTractPovertyIndicatorUtils.computePovertyIndicator() you compute the year category based on the year. So for example, category3 is for year 2008. But the CSV file names don't correspond to those years (only the two first file agree on the year range); so for example, the name of the data file for category3 is "poverty-indicator-2006-2010.csv". I find that very confusing. Why not calling the file "poverty-indicator-2008.csv"?

This might have something to do with where the data is coming from, and maybe this legit and correct this way (so the year in the filename is not the same concept as the year used for the categories). But if that's the case, I would like to add more comments in my new code to explain that...

**Comment by howew** [comment]
I think the changes look good.  

I agree that the naming convention isn't great.  I may have been just following what was done elsewhere in the project.  Part of the issue with setting the category name based on the midpoint is that the ranges can change over the years - especially in the more recent years... so it will be a lot of places to update in the code when that happens.  The current naming convention also makes it easier to compare changes from 1 year to the next because you don't have to deal with variable names changing in addition to other changes (new years added).

**Comment by depryf** [comment]
That sounds good, I just wanted to make sure. I will add a comment when mapping the file names to the category so it's clear. Thanks.

**Comment by depryf** [comment]
This has been merged.
