### ISSUE TITLE
Congressional districts update

### ISSUE THREAD

**Issue by howew** [imsweb/algorithms#190]
The lookup table needs to be updated.  The revised table is in the same excel file as the one attached to the epht issue.

Set version = 2.0, and description = 118th congress with 2010 boundaries.

**Comment by depryf** [comment]
The data now comes from the SEER data file:

https://seer.cancer.gov/seerstat/variables/countyattribs/ctattrdict.html

We will need that data file to be updated/released on the SEER website before this issue can be resolved.

**Comment by depryf** [comment]
The Congressional District data is contained in the SEER data posted on the SEER website, but we are not currently using it (we use a standalone CSV to load that data).

I believe we want to switch to the SEER data, but it it's a 4-characters code instead of a 2-digits code (it contains the state as a prefix).  We are trying to determine if it's OK to switch to the 4-characters code in this library, or if we want to stick with the 2 digits...

**Comment by depryf** [comment]
I switched to the SEER data and I am removing the state prefix so the output is the same as before.

If we want to include the state, it's a very simple change. We will need another issue for that.
