### ISSUE TITLE
Vital status 0 should be used instead of 4 for dead.

### ISSUE THREAD

**Issue by bekeles** [imsweb/algorithms#29]
All algorithms should be checked. CauseSpecific is one of them,

**Comment by depryf** [comment]
Actually, I think we should change "4" to "4 or 0" instead of changing it to "0".

That way old data file will still correctly use the algorithms, and I don't see any bad side effect in still allowing the old value.

@halla-ims can you please take a look at the different algorithms and identify (and fix) the ones that use vital status? Thanks.

Once you are done, can you please add an entry in the CHANGELOG.md file? Thanks.

**Comment by depryf** [comment]
Changes have been merged, they will be available in version 1.13.
