### ISSUE TITLE
Unknown country code in NHIA algorithm

### ISSUE THREAD

**Issue by WerthPADOH** [imsweb/algorithms#49]
In the line below, I'm not sure which country `"SWK"` is.  I didn't find it in the ISO-3166 table or [SEER's country codes](https://seer.cancer.gov/manuals/2018/SPCSM_2018_AppendixB.pdf).

https://github.com/imsweb/algorithms/blob/b02faa92f1abb992a18387cca4abddae52cb3420/src/main/java/com/imsweb/algorithms/nhia/NhiaUtils.java#L81

**Comment by depryf** [comment]
"SWK" is the old SEER code for "Slovakia", but it was changed to "SVK" a few years ago. I am not sure why this algorithm was not updated (especially since I see other country codes that were updated).

I am going to investigate a little bit more before fixing this.

**Comment by depryf** [comment]
This library is supposed to implement the same logic as the corresponding SAS program provided by NAACCR (https://www.naaccr.org/analysis-and-data-improvement-tools/#NHAPIIA). It turns out that program is also missing the new "SVK" code. That is going to be fixed and a new version is going to be uploaded on the NAACCR website; when that happens, I will add the new code to this library as well.

**Comment by depryf** [comment]
The SAS code has not been fixed yet, but it should be soon. Since this library is going to be released soon, I added the missing "SVK" code to that list.
