### ISSUE TITLE
IarcUtils null pointer exception

### ISSUE THREAD

**Issue by howew** [imsweb/algorithms#82]
Line 215 of IarcUtils (shown below), which is part of the InternalRecDto constructor, can throw a null pointer exception.
`_seqNum = record.getSequenceNumber();`

This happens when a patient has more than 1 tumor and one of the tumors is missing the sequence number.  The problem is that the sequence number in the IarcMpInputRecordDto object is an Object of type Integer and it's being assigned to the sequence number of the InternalRecDto which is a primitive int.

**Comment by depryf** [comment]
This is fixed and unit tested. Note that since the sequence is used in the tumor comparison logic, having some tumors without a sequence basically results in an indeterminate result. It won't crash, but the results won't be meaningful. This algorithm doesn't really have unknown values, and so that's just the best we can do for invalid inputs...
